[2024-12-18T09:56:36.721+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-18T09:56:36.784+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_mongodb.etl_mongo_to_clickhouse scheduled__2024-12-18T00:00:00+00:00 [queued]>
[2024-12-18T09:56:36.805+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_mongodb.etl_mongo_to_clickhouse scheduled__2024-12-18T00:00:00+00:00 [queued]>
[2024-12-18T09:56:36.805+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-18T09:56:36.845+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): etl_mongo_to_clickhouse> on 2024-12-18 00:00:00+00:00
[2024-12-18T09:56:36.905+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=180) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-18T09:56:36.910+0000] {standard_task_runner.py:72} INFO - Started process 202 to run task
[2024-12-18T09:56:36.933+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_mongodb', 'etl_mongo_to_clickhouse', 'scheduled__2024-12-18T00:00:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpb5l0tb8e']
[2024-12-18T09:56:36.941+0000] {standard_task_runner.py:105} INFO - Job 58: Subtask etl_mongo_to_clickhouse
[2024-12-18T09:56:37.093+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_mongodb.etl_mongo_to_clickhouse scheduled__2024-12-18T00:00:00+00:00 [running]> on host ea437989725c
[2024-12-18T09:56:37.819+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Tohid' AIRFLOW_CTX_DAG_ID='etl_mongodb' AIRFLOW_CTX_TASK_ID='etl_mongo_to_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2024-12-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-18T00:00:00+00:00'
[2024-12-18T09:56:37.820+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-18T09:56:37.822+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-18T09:56:37.823+0000] {logging_mixin.py:190} INFO - Current task name:etl_mongo_to_clickhouse state:running start_date:2024-12-18 09:56:36.785200+00:00
[2024-12-18T09:56:37.823+0000] {logging_mixin.py:190} INFO - Dag name:etl_mongodb and current dag run status:running
[2024-12-18T09:56:37.824+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-18T09:56:37.913+0000] {logging_mixin.py:190} INFO - Number of documents in 'students' collection: 10000
[2024-12-18T09:56:37.994+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/process.py", line 53, in etl
    client_clickhouse.insert('airflow.students', student_data)  # Use the 'students' table in the 'airflow' database
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/client.py", line 628, in insert
    context.data = data
    ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/insert.py", line 96, in data
    self.block_row_count = self._calc_block_size()
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/insert.py", line 118, in _calc_block_size
    d_size = d_type.data_size(sample)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/datatypes/base.py", line 106, in data_size
    d_size = self._data_size(sample)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/datatypes/string.py", line 30, in _data_size
    total += len(x)
             ^^^^^^
TypeError: object of type 'int' has no len()
[2024-12-18T09:56:38.017+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-18T09:56:38.020+0000] {logging_mixin.py:190} INFO - Task start:2024-12-18 09:56:36.785200+00:00 end:2024-12-18 09:56:38.017182+00:00 duration:1.231982
[2024-12-18T09:56:38.021+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): etl_mongo_to_clickhouse> dag:<DAG: etl_mongodb> dagrun:<DagRun etl_mongodb @ 2024-12-18 00:00:00+00:00: scheduled__2024-12-18T00:00:00+00:00, state:running, queued_at: 2024-12-18 09:55:22.630915+00:00. externally triggered: False>
[2024-12-18T09:56:38.022+0000] {logging_mixin.py:190} INFO - Failure caused by object of type 'int' has no len()
[2024-12-18T09:56:38.022+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_mongodb, task_id=etl_mongo_to_clickhouse, run_id=scheduled__2024-12-18T00:00:00+00:00, execution_date=20241218T000000, start_date=20241218T095636, end_date=20241218T095638
[2024-12-18T09:56:38.062+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-18T09:56:38.066+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 58 for task etl_mongo_to_clickhouse (object of type 'int' has no len(); 202)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/process.py", line 53, in etl
    client_clickhouse.insert('airflow.students', student_data)  # Use the 'students' table in the 'airflow' database
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/client.py", line 628, in insert
    context.data = data
    ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/insert.py", line 96, in data
    self.block_row_count = self._calc_block_size()
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/driver/insert.py", line 118, in _calc_block_size
    d_size = d_type.data_size(sample)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/datatypes/base.py", line 106, in data_size
    d_size = self._data_size(sample)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_connect/datatypes/string.py", line 30, in _data_size
    total += len(x)
             ^^^^^^
TypeError: object of type 'int' has no len()
[2024-12-18T09:56:38.117+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-18T09:56:38.141+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
